#!/bin/sh

regex='@outlook\.com$'

email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
    echo Your email address $email satisfies Git policy
    exit 0
else
    echo Your email address $email does not satisfy Git policy
    exit 1
fi